project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "BIOL340 - Autumn 2025"
  description: "Homepage for BIOL340 Dry Pracs, University of Wollongong, Autumn 2025."
  site-url: "https://nikolasjohnston.github.io/BIOL340_DP/"

  repo-url: https://github.com/nikolasjohnston/BIOL340_DP
  repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Nikolas Johnston"
    background: "#de2626"

  sidebar:
    background: "#de2626"
    logo: "images/2025_header.png"
    pinned: true
    align: center
 
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Introduction"
        contents:
          - href: pages/introduction/01_R-studio-and-the-coding-environment.qmd
            text: 01 R studio and the coding environment
          - href: pages/introduction/02_Setting-up-your-workspace.qmd
            text: 02 Setting up your workspace
      - section: "Data exploration and manipulation"
        contents:

      - section: "Grammar of Graphics"
        contents:

      - section: "Dry Prac 1 Activites"
        contents:
    
       
      - section: "Supplemental notes"
        contents:


format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual


