project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "BIOL340 - Autumn 2025"
  description: "Homepage for BIOL340 Dry Pracs, University of Wollongong, Autumn 2025."
  site-url: "https://nikolasjohnston.github.io/BIOL340_DP/"

  repo-url: https://github.com/nikolasjohnston/BIOL340_DP
  repo-actions: [edit, issue]
  
  open-graph: true

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Nikolas Johnston"
    background: "#960e0c"

  sidebar:
    background: "#960e0c"
    logo: "images/2025_header.png"
    pinned: true
    align: center
 
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Pre-Lab - Introduction"
        contents:
          - href: pages/introduction/01_R-studio-and-the-coding-environment.qmd
            text: R studio and the coding environment
          - href: pages/introduction/02_Setting-up-your-workspace.qmd
            text: Setting up your workspace
          - href: pages/introduction/03_Creating-a-project.qmd
            text: Creating a project
          - href: pages/introduction/4_notebooks.qmd
            text: Notbooks in R studio
            
      - section: "Pre-Lab - Data exploration"
        contents:
          - href: pages/1/1_packages.qmd
            text: Packages
          - href: pages/1/2_viewingdata.qmd
            text: Viewing Data
          - href: pages/1/3_columns.qmd
            text: Columns
            

         
            
      - section: "Dry Prac 1"
        contents: 
        - href: pages/DP1/DP1_Final.qmd
          text: Dry Prac 1 Notes


      - section: "Pre-Lab 2 - Data manipulation"
        contents:
          - href: pages/1/1_rename.qmd
            text: The Rename function
          - href: pages/1/2_mutate.qmd
            text: The Mutate function
          - href: pages/1/3_filter.qmd
            text: The Filter function
          - href: pages/1/4_Select.qmd
            text: The Select function
          - href: pages/1/7_summarise.qmd
            text: The Summarise function
          - href: pages/1/8_pipe.qmd
            text: The Pipe function
          
      - section: "Dry Prac 2"
        contents: 
          - href: pages/DP2/DP2_Final.qmd
            text: Dry Prac 1 Notes
  
      - section: "Extra help with Graphics"
        contents:
        - href: pages/2/1_ggplotgrammar.qmd
          text: Graphics in ggplot2
        - href: pages/2/2_basicplots.qmd
          text: Basic plots
        - href: pages/supplementary/cheetsheet.qmd
          text: Additional ggplot2 support
            
        - section: "Themes a customisation in ggplot2"
          contents:        
          - href: pages/2/Themes/3_themes.qmd
            text: Themes introduction
          - href: pages/2/Themes/4_gridsbackground.qmd
            text: Backgrounds
          - href: pages/2/Themes/5_axislines.qmd
            text: Axis lines
          - href: pages/2/Themes/6_grids.qmd
            text: Grids
          - href: pages/2/Themes/7_axislabels.qmd
            text: Axis labels
          - href: pages/2/Themes/8_properexamples.qmd
            text: Examples


format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    
include-in-header:

  text: |
    <style type="text/css">
    .quarto-reader-toggle .bi::before, .quarto-color-scheme-toggle .bi::before {
      display: flex;
      height: 2rem;
      width: 2rem;
      gap: 0.5rem;
      background-size: 2rem 2rem;
      font-size: 1rem;
      font-family: sans-serif;
      display: inline-block;
    }

    .quarto-reader-toggle::before, .quarto-color-scheme-toggle::before {
        content: "Dark Mode";
        display: flex;
        font-size: 1rem;
        gap: 0.5rem;
        font-family: Atkinson Hyperlegible, sans-serif;
    </style>
    
freeze: auto

editor: visual

