---
title: "BIOL340_DP"
---

# Welcome to Biol340 Dry Practicals for 2025

# Staring At R 

This site is a series of tutorials on using the R statistical package for data manipulation, analysis and visualisation including the following:  

* Setting up your file system and working environment in a reproducable manner  
* Viewing and manipulating your data 
* Statistical analysis, covering analysis of variance, linear regressions and generalised linear models (more to come!)  
* Visualisation of your results using an iterative graphing approach  
* Spatial analysis and map creation (work in progress)  

It also includes specific tutorials to complete within the Dry Practical timeslot during session.


I am entirely self-taught through online tutorials, textbooks and advice from colleagues. The best advice I can give is to put in the time and effort. Force yourself to work through problems in R, rather than resorting to excel or your known statistical package. Spending the time to learn R and using it frequently will reinforce lessons and how to utilise code, this goes for all coding languages.  

This site has been large developed as an offshot and extension of [staringatr.com](https://staringatr.com) created by [Dr. Mitchell Stares](https://mitchstares.github.io/). The initial focus of this site is data science techniques for biology based research, however, this will hopefully improve in scope in the future. Tutorials have been developed as part of a teaching module for undergraduate students in the School of science at the [University of Wollongong](https://www.uow.edu.au/index.html) but have been expanded beyond that initial development.

This website was created using Quarto. To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

**Site administrator:** [Dr. Nikolas Johnston](https://scholars.uow.edu.au/nikolas-johnston)
Last updated: March 2025.